blank_issues_enabled: false
contact_links:
    - name: 💬 GitHub Discussions
      url: https://github.com/ralphschuler/openmediavault-plugins/discussions
      about: Ask questions, share ideas, and discuss with the community
    - name: 📖 Documentation
      url: https://github.com/ralphschuler/openmediavault-plugins/blob/main/README.md
      about: Read the project documentation and plugin guides
    - name: 🔒 Security Issues
      url: https://github.com/ralphschuler/openmediavault-plugins/blob/main/SECURITY.md
      about: Report security vulnerabilities privately (do not use public issues)
