#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if [ -x /usr/share/openmediavault/mkconf/immich ]; then
        /usr/share/openmediavault/mkconf/immich remove || true
    fi
fi

exit 0
