name: Build & Release OMV Plugin

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Debian build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y debhelper devscripts lintian dpkg-dev build-essential

      - name: Build .deb package
        env:
          DEBFULLNAME: Inhaus AI
          DEBEMAIL: dev@inhaus.ai
        run: |
          dpkg-buildpackage -b -us -uc

      - name: Lint package
        run: lintian ../*.deb || true

      - uses: actions/upload-artifact@v4
        with:
          name: deb
          path: ../*.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: deb

      - uses: softprops/action-gh-release@v1
        with:
          files: '*.deb'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
