---
name: Lint & Format

"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  python-lint:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - name: Check Python formatting with Black
        run: black --check --diff scripts/ openmediavault-*/src/usr/share/openmediavault/engined/rpc/

      - name: Check imports with isort
        run: isort --check-only --diff scripts/ openmediavault-*/src/usr/share/openmediavault/engined/rpc/

      - name: Lint with flake8
        run: flake8 scripts/ openmediavault-*/src/usr/share/openmediavault/engined/rpc/

  javascript-lint:
    name: JavaScript Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JavaScript linting tools
        run: |
          npm install -g eslint prettier

      - name: Lint JavaScript files
        run: |
          if find . -name "*.js" -path "*/openmediavault-*" | grep -q .; then
            find . -name "*.js" -path "*/openmediavault-*" -exec eslint {} +
          else
            echo "No JavaScript files found to lint"
          fi

      - name: Check JavaScript formatting
        run: |
          find . -name "*.js" -path "*/openmediavault-*" -exec prettier --check {} +

  shell-lint:
    name: Shell Script Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Lint shell scripts
        run: |
          find . -type f \( -name "*.sh" -o -name "mkconf" -o -name "postinst" -o -name "prerm" \) \
            -path "*/openmediavault-*" -exec shellcheck {} +

  yaml-lint:
    name: YAML Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint YAML files
        run: |
          find . -name "*.yml" -o -name "*.yaml" | xargs yamllint
